### ISSUE TITLE
[BUG] New version contains <shuffle> err

### ISSUE THREAD

**Issue by ehdtn7196** [FungY911/better-grass#15]
I download new version to 2 PCs with clean state

and "ReferenceError: shuffle is not defined" appears

below the logs 

0|better-grass  | ReferenceError: shuffle is not defined
0|better-grass  |     at initializeIpAddresses (/usr/bin/better-grass/src/app.js:297:19)
0|better-grass  |     at Object.<anonymous> (/usr/bin/better-grass/src/app.js:318:1)
0|better-grass  |     at Module._compile (node:internal/modules/cjs/loader:1159:14)
0|better-grass  |     at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
0|better-grass  |     at Module.load (node:internal/modules/cjs/loader:1037:32)
0|better-grass  |     at Module._load (node:internal/modules/cjs/loader:878:12)
0|better-grass  |     at Object.<anonymous> (/usr/local/lib/node_modules/pm2/lib/ProcessContainerFork.js:33:23)
0|better-grass  |     at Module._compile (node:internal/modules/cjs/loader:1159:14)
0|better-grass  |     at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
0|better-grass  |     at Module.load (node:internal/modules/cjs/loader:1037:32)

**Comment by FungY911** [comment]
Hey, I fixed it in the last Hey, I fixed it in the last commit. This is not tested for grass server maintenance
